### ISSUE TITLE
Conventional mill design with rotary table without Y axis

### ISSUE THREAD

**Issue by Vorlent** [kadirilkimen/Polar-Bear-Cnc-Machine#2]
Start with a conventional mill and remove the Y axis. Add the rotary table on top of an X axis.

One big problem with this idea is that the spindle has to align with the center of the rotary table on the Y axis which was removed in this design. On the plus side the rotary table allows you to get to the other side meaning that no space is wasted on where the Y axis would be. If the design is still lacking in rigidity you could use a design similar to a CNC router with basically a column on both sides.

[Sketch](https://i.imgur.com/OKNSXip.png)

The head can be tilted 90°.

Disclaimer: I haven't touched or built a CNC machine in real life.

**Comment by kadirilkimen** [comment]
Your suggestions do not improve PolarBear. It makes it a different design.
It also takes away some pros of the Polar Bear.

Current design is simple.  It requires less materials to build and has some pros compared to other kind of desktop machine concepts.
